name: murait_cli
description: A Flutter code generator CLI for GetX and BLoC architecture (with model and repository support).
version: 0.0.1
repository: https://github.com/yourname/murait_cli   # optional but recommended
homepage: https://your-website.com                   # optional
issue_tracker: https://github.com/yourname/murait_cli/issues  # optional

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  args: ^2.5.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.0

executables:
  murait_cli:
